CAProjectV2/Controllers/LogInController.cs
using CAProjectV2.Data;
using CAProjectV2.Logic;
using CAProjectV2.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace CAProjectV2.Controllers
{
    public class LogInController : Controller
    {
        public IActionResult Index()
        {
            string loginUser = HttpContext.Session.GetString("Userid");

            return View();
        }

        private readonly WebsiteContext _context;

        public LogInController(WebsiteContext context)
        {
            _context = context;
        }

        public  IActionResult Login(LogInViewModel logInUser)
        {
            
            var password = Encrption.Encrypt(logInUser.Password);
            User result =  _context.User.Where(x => x.UserName == logInUser.UserName 
                                               && x.Password == password)
                                        .FirstOrDefault();
            if (result != null)
            {
                HttpContext.Session.SetString("Userid", result.Id);
                HttpContext.Session.SetString("isLogin", result.UserName);
           
                string guestLogin = Request.Cookies["GuestLogin"];

                var items = _context.ShoppingCartItem.Where(x => x.UserId == guestLogin);
                                                    
                
                if (items != null)
                {

                    string userLogin = HttpContext.Session.GetString("Userid");
                    foreach (var item in items)
                    {
                        item.UserId = userLogin;
                    }

                    _context.SaveChanges();

                }
               
                return RedirectToAction("Index", "Products");  
         

            }
            
            TempData["loginStatus"] = true;
            return Redirect("Index");  
            

        }

        
    }
}

CAProjectV2/Controllers/LogOutController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;

namespace CAProjectV2.Controllers
{
    public class LogOutController : Controller
    {
        public IActionResult Index()
        {
            if (!String.IsNullOrEmpty(HttpContext.Session.GetString("isLogin")))
                HttpContext.Session.Clear();
            else
                return RedirectToAction("Index", "LogIn");
            
            return View();
        }
    }
}

CAProjectV2/Controllers/ProfileController.cs
using CAProjectV2.Data;
using CAProjectV2.Logic;
using CAProjectV2.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CAProjectV2.Controllers
{
    public class ProfileController : Controller
    {
        

        private readonly WebsiteContext _context;

        public ProfileController(WebsiteContext context)
        {
            _context = context;
        }

        public IActionResult RenderProfile()
        {
          

            if (!String.IsNullOrEmpty(HttpContext.Session.GetString("isLogin"))){    //checking session is null or not which means checking user log in or out

                var id = HttpContext.Session.GetString("Userid");
                User user = _context.User.AsNoTracking().Where(x => x.Id == id).FirstOrDefault();
                ProfileViewModel pf = new ProfileViewModel(user.UserImageUrl, user.FirstName, user.LastName, user.UserName, user.Email, user.PhoneNumber, "", "");

                ViewData["profile"] = pf;

                string guestLogin = HttpContext.Session.GetString("isLogin");
                ViewData["isLogin"] = guestLogin;
                return View(pf);
            }
            else
            {

                return RedirectToAction("Index", "LogIn");                           //if not log in, render login page
            }
        }

        public IActionResult Edit()
        {
            if (!String.IsNullOrEmpty(HttpContext.Session.GetString("isLogin")))
            {    //checking session is null or not which means checking user log in or out

                var id = HttpContext.Session.GetString("Userid");
                User user = _context.User.AsNoTracking().Where(x => x.Id == id).FirstOrDefault();
                ProfileViewModel pf = new ProfileViewModel(user.UserImageUrl, user.FirstName, user.LastName, user.UserName, user.Email, user.PhoneNumber, "", "");
                return View(pf);
            }
            else
            {

                return RedirectToAction("Index", "LogIn");                           //if not log in, render login page
            }
        }

        [HttpPost]
        public async Task<IActionResult> EditProfile(ProfileViewModel profile, IFormFile UserImageUrl)
        {

            if (UserImageUrl != null && UserImageUrl.Length > 0)
            {
                var fileName = Path.GetFileName(UserImageUrl.FileName);
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", fileName);
                using (var fileSteam = new FileStream(filePath, FileMode.Create))
                {
                    await UserImageUrl.CopyToAsync(fileSteam);
                }
                profile.UserImageUrl = fileName;
            }

            var oldPassword = Encrption.Encrypt(profile.OldPassword);
            User result = _context.User.Where(x => x.UserName == profile.UserName && x.Password == oldPassword).FirstOrDefault();
            if (result != null) {
                var id = HttpContext.Session.GetString("Userid");                //validate recent login user by calling session id
                User user = _context.User.Where(x => x.Id == id).FirstOrDefault();
                user.UserName = profile.UserName;
                user.FirstName = profile.FirstName;
                user.LastName = profile.LastName;
                user.Email = profile.Email;     
                user.PhoneNumber = profile.PhoneNumber;
                if (!string.IsNullOrEmpty(profile.UserImageUrl))
                {
                    user.UserImageUrl = profile.UserImageUrl;
                }
                if (!string.IsNullOrEmpty(profile.NewPassword)) {
                    user.Password = Encrption.Encrypt(profile.NewPassword);
                }
                _context.SaveChanges();

                return RedirectToAction("RenderProfile");
            }
            return RedirectToAction("Error");
        }


    }
}

CAProjectV2/Controllers/RegisterController.cs
using CAProjectV2.Data;
using CAProjectV2.Logic;
using CAProjectV2.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CAProjectV2.Controllers
{
    public class RegisterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        private readonly WebsiteContext _context;

        public RegisterController(WebsiteContext context)
        {
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> RegisterUser(User user, IFormFile UserImageUrl)  // IFormFile, provided by .net framework -> when files are uploaded, they are saved in temporary storage, from that storage, IFormFile take those fils and put into wwwroot/
            {
            var files = HttpContext.Request.Form.Files;
            if (UserImageUrl != null && UserImageUrl.Length > 0)
            {
                var fileName = Path.GetFileName(UserImageUrl.FileName);
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await UserImageUrl.CopyToAsync(fileStream);
                }
                user.UserImageUrl = fileName;
            }

            user.Id = IdGenerator.ID();
            user.Password = Encrption.Encrypt(user.Password);
            var validateUser = _context.User.Where(x => x.UserName == user.UserName || x.Email == user.Email).FirstOrDefault();
            if (validateUser == null)
            {
                await _context.User.AddAsync(user);
                 _context.SaveChanges();
                
            }
            else {
                TempData["userDuplicate"] = true;
                return Redirect("Index");    // UI : need to show error message/page that user alr exit
            }
            return RedirectToAction("Index", "LogIn");
        }
    }
}

CAProjectV2/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

@{ 
    
    ProfileViewModel user = (ProfileViewModel)@ViewData["profile"];
    string Is_Product = (string)ViewData["Is_Product"];
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  

    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
    <link href="~/css/bootstrap-reboot.css" rel="stylesheet" />
    <link href="~/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/main.css" rel="stylesheet" />



</head>

<body>


    <div class="container-fluid zero-padding">

        <div class="header-row">
            <div class="header-row__top row clearfix">
                <a class="header-row__logo row" style="margin-left : 20px;width:336px" asp-area="" asp-controller="Home" asp-action="Index">
                    @*<div class="header-row__logo_content">
                        <div class="header-row__logo-text">.NET Team 8 Store</div>
                        <div class="header-row__logo_desc">Digital Transformation Resource</div>
                    </div>*@
                    <img src="~/images/logo.png" alt="header-row__logo" class="header-row__logo-image">

                </a>





                @if( Is_Product == "isProductPage") { 

                   <div class="search_container">

                    <form asp-area="" asp-controller="Products" asp-action="Index" method="post">
                        @*<div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-8">
                        *@
                        <div class="card-body row no-gutters align-items-center">

                            <div class="col">
                                <input class="form-control form-control-lg form-control-borderless" height="30" type="text" name="SearchString" placeholder="Enter your search here ..." value="@ViewData["CurrentFilter"]">
                            </div>
                            <!--end of col-->
                            <div class="col-auto">
                                <button type="submit" class="search_button" style="outline:none">Search</button>

                            </div>
                            <!--end of col-->
                                                     </div>
                      

                            <!--/div>-->
                            <!--end of col-->
                            <!--</div>-->
                    </form>


                </div>
                }
                else
            {
                <div></div>
            }
                @if (!String.IsNullOrEmpty(Context.Session.GetString("Userid")))
                {

                    <a asp-area="" asp-controller="Profile" asp-action="RenderProfile" class="align-self-center" style="margin-right:30px">

                        <div class="row">

                            <img class="header-row__profile rounded-circle" src="@Url.Content("~/images/" + user.UserImageUrl)" />
                            <div class="header-row__profile-content">
                                <div class="header-row__profile-name">@user.FirstName @user.LastName</div>
                                <div class="header-row__profile-email">@user.Email</div>
                            </div>
                        </div>
                    </a>
                }
               
            </div>
            <div class="row-header__main">
                <ul class="header-row__menu align-self-center col-12">
                    <li class="header-row__menu-item"><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><span class="menu_item">Home</span></a></li>
                    <li class="header-row__menu-item"><a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index"><span class="menu_item">Products</span></a></li>

                    <li class="header-row__menu-item"><a class="nav-link text-dark" asp-area="" asp-controller="WishItem" asp-action="WishList"><span class="menu_item">My Wishlist</span></a></li>
                    @if (!String.IsNullOrEmpty(Context.Session.GetString("Userid")))
                    {
                        <li class="header-row__menu-item"> <a class="nav-link text-dark" asp-area="" asp-controller="OrderDetails" asp-action="Index"><span class="menu_item">My Purchase History</span></a></li>
                        <li class="header-row__menu-item"><a class="nav-link text-dark" asp-area="" asp-controller="LogOut" asp-action="Index"><span class="menu_item">Logout</span></a></li>

                    }
                    else
                    {
                        <li class="header-row__menu-item"><a class="nav-link text-dark" asp-area="" asp-controller="LogIn" asp-action="Index"><span class="menu_item">Login</span></a></li>
                        <li class="header-row__menu-item"><a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Index"><span class="menu_item">Register</span></a></li>


                    }
                    <li class="header-row__menu-item">
                        <a href="/ShoppingCartItems/Index" class="cart position-relative d-inline-flex" aria-label="View your shopping cart">
                            <i class="fas fa fa-shopping-cart fa-2x" style="font-size:25px"></i>
                            <span id="shoppingcartcount" class="cart_count"></span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="footer_bottom">
        <div class="container_footer">
            &copy; 2021 - Shopping Cart Application

        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/wishitem.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/main.css" rel="stylesheet" />

    @RenderSection("Scripts", required: false)
</body>
</html>