CAProjectV2/Models/ShoppingCartItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;


namespace CAProjectV2.Models
{
    public class ShoppingCartItem
    {
        //Maybe we can use the sessionId as 
        [Column("ShoppingCartItemId")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        
        public string Id { get; set; }
        public string ShoppingCartId { get; set; }
        public string ShoppingCartItemEachProductId { get; set; }
        public string UserId { get; set; }
        public string ProductId { get; set; }
        public int Quantity { get; set; }



        public virtual Product Product {get;set;}
    }
}

CAProjectV2/Controllers/ShoppingCartItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CAProjectV2.Data;
using CAProjectV2.Models;
using CAProjectV2.Logic;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;

namespace CAProjectV2.Controllers
{//testing 
    public class ShoppingCartItemsController : Controller
    {
        private readonly WebsiteContext _context;

        public ShoppingCartItemsController(WebsiteContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Adding(ShoppingCartItem items)
        {
            items.Id = IdGenerator.ID();
            items.ShoppingCartId = IdGenerator.ID();
            items.ShoppingCartItemEachProductId = items.Id.Clone().ToString() + items.ShoppingCartId.Clone().ToString();
            items.Quantity = 1;

            if (!String.IsNullOrEmpty(HttpContext.Session.GetString("isLogin")))
                items.UserId = HttpContext.Session.GetString("Userid"); 
            else
                items.UserId = Request.Cookies["GuestLogin"];

            await _context.AddAsync(items);
            await _context.SaveChangesAsync();

            var _exists = _context.WishList
                                    .Where(x => x.UserId == items.UserId
                                    && x.ProductId == items.ProductId)
                                    .FirstOrDefault();

            if (_exists != null)
                _context.WishList.Remove(_exists);

            await _context.SaveChangesAsync();

            return LocalRedirect("/Products/Index");
        }

        public async Task<IActionResult> Addinginwishlist(ShoppingCartItem items)
        {
            items.Id = IdGenerator.ID();
            items.ShoppingCartId = IdGenerator.ID();
            items.ShoppingCartItemEachProductId = items.Id.Clone().ToString() + items.ShoppingCartId.Clone().ToString();
            items.Quantity = 1;
            if (!String.IsNullOrEmpty(HttpContext.Session.GetString("isLogin")))
                items.UserId = HttpContext.Session.GetString("Userid");
            else
                items.UserId = Request.Cookies["GuestLogin"];

            await _context.AddAsync(items);
            await _context.SaveChangesAsync();

            var _exists = _context.WishList
                .Where(x => x.UserId == items.UserId
                && x.ProductId == items.ProductId)
                .FirstOrDefault();

            if (_exists != null)
                _context.WishList.Remove(_exists);

            await _context.SaveChangesAsync();

            return LocalRedirect("/WishItem/WishList");
        }

        [HttpPost]
        public async Task<IActionResult> Updating(ShoppingCartItem updatedQty)
        {
            //if the qty is lesser than the update quantity, delete until the qty is equal to the updatedQty

            //list of items in the shopping cart database
            var products = _context.ShoppingCartItem
                            .Where(x => x.UserId == updatedQty.UserId 
                                && x.ProductId == updatedQty.ProductId)
                            .ToList();

            //find original qty
            var websiteContext = _context.ShoppingCartItem.Where(x => x.UserId == updatedQty.UserId).Count(x =>
            Convert.ToString(x.ProductId) == Convert.ToString(updatedQty.ProductId));

            if (updatedQty.Quantity > 0)
            {
                //generating new productid details for this updatedQty
                updatedQty.Id = IdGenerator.ID();
                updatedQty.Quantity = 1;
                await _context.ShoppingCartItem.AddAsync(updatedQty);
                await _context.SaveChangesAsync();
                
            }
            else
            {
                _context.ShoppingCartItem.Remove(products.FirstOrDefault());
                await _context.SaveChangesAsync();

            }

            return RedirectToAction(nameof(Index));
        }

        //GET: ShoppingCartItems
        //public async Task<IActionResult> Index()
        //{
        //    var websiteContext =  _context.ShoppingCartItem.Include(s => s.Product);

        //    return View(await websiteContext.ToListAsync());
        //}

        public IActionResult Index()
        {
             if (!String.IsNullOrEmpty(HttpContext.Session.GetString("isLogin")))
            {    //checking session is null or not which means checking user log in or out

                var id = HttpContext.Session.GetString("Userid");
                User user = _context.User.AsNoTracking().Where(x => x.Id == id).FirstOrDefault();
                ProfileViewModel profile = new ProfileViewModel(user.UserImageUrl, user.FirstName, user.LastName, user.UserName, user.Email, user.PhoneNumber, "", "");
                ViewData["profile"] = profile;
             
            }

            string currentLogin;
            if (!String.IsNullOrEmpty(HttpContext.Session.GetString("isLogin")))
            {
                currentLogin = HttpContext.Session.GetString("Userid");
            }
            else
            {
                currentLogin = Request.Cookies["GuestLogin"];
            }

            //var websiteContext = _context.ShoppingCartItem.Include(s => s.Product).ToList();
            var websiteContext = _context.ShoppingCartItem.Include(s => s.Product)
                .Where(x => x.UserId == currentLogin)
                .OrderBy(x => x.Product.ProductName)
                .ToList();

            ViewData["Data"] = websiteContext;
            string guestLogin = HttpContext.Session.GetString("isLogin");
            ViewData["isLogin"] = guestLogin;
            //var product = from p in _context.ShoppingCartItem
            //              select  p.ProductId.Distinct();
            //ViewData["productcount"] = product;

            return View();
        }

        // GET: ShoppingCartItems/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoppingCartItem = await _context.ShoppingCartItem
                .Include(s => s.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shoppingCartItem == null)
            {
                return NotFound();
            }

            return View(shoppingCartItem);
        }

        // GET: ShoppingCartItems/Create
        public IActionResult Create()
        {
            ViewData["ProductId"] = new SelectList(_context.Product, "Id", "Id");
            return View();
        }

        // POST: ShoppingCartItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ShoppingCartId,ShoppingCartItemEachProductId,UserId,ProductId,Quantity")] ShoppingCartItem shoppingCartItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shoppingCartItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Product, "Id", "Id", shoppingCartItem.ProductId);
            return View(shoppingCartItem);
        }

        // GET: ShoppingCartItems/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoppingCartItem = await _context.ShoppingCartItem.FindAsync(id);
            if (shoppingCartItem == null)
            {
                return NotFound();
            }
            ViewData["ProductId"] = new SelectList(_context.Product, "Id", "Id", shoppingCartItem.ProductId);
            return View(shoppingCartItem);
        }

        // POST: ShoppingCartItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,ShoppingCartId,ShoppingCartItemEachProductId,UserId,ProductId,Quantity")] ShoppingCartItem shoppingCartItem)
        {
            if (id != shoppingCartItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shoppingCartItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShoppingCartItemExists(shoppingCartItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Product, "Id", "Id", shoppingCartItem.ProductId);
            return View(shoppingCartItem);
        }

        // POST: ShoppingCartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string userId, string productId)
        {
            var products = _context.ShoppingCartItem
                    .Where(x => x.UserId == userId
                            && x.ProductId == productId);

            foreach (var product in products)
            {

CAProjectV2/Views/ShoppingCartItems/Create.cshtml
@model CAProjectV2.Models.ShoppingCartItem

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>ShoppingCartItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShoppingCartId" class="control-label"></label>
                <input asp-for="ShoppingCartId" class="form-control" />
                <span asp-validation-for="ShoppingCartId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShoppingCartItemEachProductId" class="control-label"></label>
                <input asp-for="ShoppingCartItemEachProductId" class="form-control" />
                <span asp-validation-for="ShoppingCartItemEachProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class ="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CAProjectV2/Views/ShoppingCartItems/Delete.cshtml
@model CAProjectV2.Models.ShoppingCartItem

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ShoppingCartItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShoppingCartId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShoppingCartId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShoppingCartItemEachProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShoppingCartItemEachProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CAProjectV2/Views/ShoppingCartItems/Details.cshtml
@model CAProjectV2.Models.ShoppingCartItem

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>ShoppingCartItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShoppingCartId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShoppingCartId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShoppingCartItemEachProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShoppingCartItemEachProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CAProjectV2/Views/ShoppingCartItems/Edit.cshtml
@model CAProjectV2.Models.ShoppingCartItem

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>ShoppingCartItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ShoppingCartId" class="control-label"></label>
                <input asp-for="ShoppingCartId" class="form-control" />
                <span asp-validation-for="ShoppingCartId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShoppingCartItemEachProductId" class="control-label"></label>
                <input asp-for="ShoppingCartItemEachProductId" class="form-control" />
                <span asp-validation-for="ShoppingCartItemEachProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CAProjectV2/Views/ShoppingCartItems/Index.cshtml
@model IEnumerable<CAProjectV2.Models.ShoppingCartItem>

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />
<link href="~/css/button.css" rel="stylesheet" />
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link href="~/css/product.css" rel="stylesheet" />
@*<link href="~/css/main.css" rel="stylesheet" />
*@<link href="~/css/addtoCart.css" rel="stylesheet" />
@*<link href="~/css/EmptyView.css" rel="stylesheet" />
*@

@{
    ViewData["Title"] = "View Cart";

    List<ShoppingCartItem> cart = (List<ShoppingCartItem>)ViewData["Data"];
    List<ShoppingCartItem> cartdistinct = (List<ShoppingCartItem>)ViewData["productcount"];


    //Prevent duplicate items in shopping cart
    List<ShoppingCartItem> cartNoDup = new List<ShoppingCartItem>();

    foreach (var item in cart)
    {
        //if item is in cartNoDup, don't add
        ShoppingCartItem temp = cartNoDup.FirstOrDefault(m => m.ProductId == item.ProductId);

        if (temp == null)
        {
            cartNoDup.Add(item);
        }


    }
    decimal total = 0m;
    foreach (var item in cart)
    {
        total += item.Product.Price;
    }

    decimal eachTotalPrice = 0m;
    foreach (var item in cart)
    {

        {
            eachTotalPrice += item.Product.Price * item.Quantity;
        }
    }


}


@section Scripts
{

}

@if (cart.Count == 0)
{

    <div class="container-fluid mt-100">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">

                    </div>
                    <div class="card-body cart">
                        <div class="col-sm-12 empty-cart-cls text-center">
                            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvKnZN_9R2GH4ETw6DdOVNAjmefSNDDIJDWHJpIJ4YkYQnNtVqk7J4VZZDMcJam8FveAI&usqp=CAU" width="259" height="194" class="img-fluid mb-4 mr-3">
                            <h1><strong>Your Cart is Empty</strong></h1>
                            <h3>Add something to make me happy :)</h3> <a href="/Products/Index" class="btn btn-primary cart-btn-transform m-3" data-abc="true" style="font-size:20px ;padding-left : 10px;padding-right:10px;padding-top:5px;padding-bottom:5px">continue shopping</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="container_addtoCart">
        <h1><b>View Cart</b></h1>

        <div class="shopping-cart">

            <div class="column-labels">
                <label class="product-image">Image</label>
                <label class="product-details">Product</label>
                <label class="product-price">Price</label>
                <label class="product-quantity">Quantity</label>
                <label class="product-removal"> </label>
                <label class="product-line-price"> </label>
            </div>

            @foreach (var item in cartNoDup)
            {

                <div class="product">
                    <div class="product-image">
                        <img src=@item.Product.ImageUrl>
                    </div>
                    <div class="product-details">
                        <div class="product-title">@item.Product.ProductName</div>
                        <div class="product-description_long">@item.Product.Description</div>
                    </div>
                    <div class="product-price">@item.Product.Price</div>
                    <div class="product-quantity">
                        <form asp-area="" asp-controller="ShoppingCartItems" asp-action="Updating" method="post">
                            <input type="hidden" name="Id" value=@item.Id />
                            <input type="hidden" name=UserId value=@item.UserId />
                            <input type="hidden" name="ProductId" value=@item.ProductId />
                            <div class="container">
                                <button type="submit" class="minusqty" name="Quantity" value="-1" style="outline :none">-</button>
                                <input type="text" class="qty" value="@cart.Count(x => x.ProductId == item.ProductId)" />
                                <button type="submit" class="addqty" name="Quantity" value="1" style="outline :none">+</button>
                            </div>
                        </form>
                    </div>



                    <form asp-area="" asp-controller="ShoppingCartItems" asp-action="Delete" method="post">
                        <div class="product-removal_button">
                            @*<u><a class="delete_button" asp-action="Delete" asp-route-id="@item.Id">Delete</a></u>*@

                            <input type="submit" class="remove-product" style="outline:none" value="Remove" />
                            <input type="hidden" name=UserId value=@item.UserId />
                            <input type="hidden" name="ProductId" value=@item.ProductId />
                        </div>
                    </form>
                    @*
                    *@



                </div>
            }


            <div class="totals">
                
                <div class="continueShopping">
                    <a class="continueShopping" href="/Products/Index">Continue Shopping</a>
                </div>
                <div class="totals-item totals-item-total">
                    <label>Grand Total</label>
                    <div class="totals-value" id="cart-total">@total</div>
                </div>
            </div>
            <form asp-controller="OrderDetails" asp-action="Checkout" method="post">
                <input type="hidden" asp-route-id="@total" />
                <button class="checkout" style="outline:none">Checkout</button>
            </form>


        </div>

    </div>

}